/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userManualSidebar: [{type: 'autogenerated', dirName: 'user-manual'}],
  developerManualSidebar: [{type: 'autogenerated', dirName: 'developer-manual'}],
  releaseNotesSidebar: [{type: 'autogenerated', dirName: 'release-notes'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
};

export default sidebars;
